src/main/java/ec/com/redepronik/ecomprobantes/entity/Anio.java
package ec.com.redepronik.eComprobantes.entity;

public enum Anio {

	a2014("2014"), a2015("2015"), a2016("2016"), a2017("2017"), a2018("2018"), a2019("2019"), a2020("2020");

	private final String id;

	private Anio(String id) {
		this.id = id;
	}

	public String getId() {
		return id;
	}

	public static Anio obtenerPorId(String id) {
		for (Anio a : Anio.values())
			if (a.getId().compareTo(id) == 0)
				return a;
		return null;
	}
}

src/main/java/ec/com/redepronik/ecomprobantes/entity/DocumentoElectronico.java
package ec.com.redepronik.eComprobantes.entity;

import java.io.Serializable;

public class DocumentoElectronico implements Serializable {

	private static final long serialVersionUID = 1L;

	private String nombreDocumento;
	private String tipoDocumento;

	public DocumentoElectronico() {
	}

	public DocumentoElectronico(String nombreDocumento, String tipoDocumento) {
		this.nombreDocumento = nombreDocumento;
		this.tipoDocumento = tipoDocumento;
	}

	public String getNombreDocumento() {
		return nombreDocumento;
	}

	public String getTipoDocumento() {
		return tipoDocumento;
	}

	public void setNombreDocumento(String nombreDocumento) {
		this.nombreDocumento = nombreDocumento;
	}

	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

}

src/main/java/ec/com/redepronik/ecomprobantes/entity/Mes.java
package ec.com.redepronik.eComprobantes.entity;

public enum Mes {

	EN("01", "ENERO"), FE("02", "FEBRERO"), MA("03", "MARZO"), AB("04", "ABRIL"), MY("05", "MAYO"), JU("06",
			"JUNIO"), JL("07", "JULIO"), AG("08", "AGOSTO"), SE("09",
					"SEPTIEMBRE"), OC("10", "OCTUBRE"), NO("11", "NOVIEMBRE"), DI("12", "DICIEMBRE");

	private final String id;
	private final String nombre;

	private Mes(String id, String nombre) {
		this.id = id;
		this.nombre = nombre;
	}

	public String getId() {
		return id;
	}

	public String getNombre() {
		return nombre;
	}

	public static Mes obtenerPorId(String id) {
		for (Mes a : Mes.values())
			if (a.getId().compareTo(id) == 0)
				return a;
		return null;
	}

	public static Mes obtenerPorNombre(String nombre) {
		for (Mes a : Mes.values())
			if (a.getId().compareTo(nombre) == 0)
				return a;
		return null;
	}
}

src/main/java/ec/com/redepronik/ecomprobantes/controller/DocumentosRecibidosBean.java
package ec.com.redepronik.eComprobantes.controller;

import static ec.com.redepronik.eComprobantes.utils.Utils.fechaFormatoString;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.annotation.PostConstruct;

import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import ec.com.redepronik.eComprobantes.entity.Anio;
import ec.com.redepronik.eComprobantes.entity.DocumentoElectronico;
import ec.com.redepronik.eComprobantes.entity.Mes;
import ec.com.redepronik.eComprobantes.service.DocumentosElectronicosService;

@Controller
@Scope("session")
public class DocumentosRecibidosBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Autowired
	private DocumentosElectronicosService documentosElectronicosService;

	private List<DocumentoElectronico> listaDocumentosAutorizados;
	private StreamedContent documento;
	private Mes mes;
	private Anio anio;

	public DocumentosRecibidosBean() {
	}

	public Mes[] getListaMes() {
		return Mes.values();
	}

	public Anio[] getListaAnio() {
		return Anio.values();
	}

	public void descargarXML(DocumentoElectronico documentoElectronico) {
		String nomDocmento = documentoElectronico.getNombreDocumento() + ".xml";
		documento = new DefaultStreamedContent(documentosElectronicosService.getFileRIDE(nomDocmento), "text/xml",
				nomDocmento);
	}

	public void descargarRIDE(DocumentoElectronico documentoElectronico) {
		String nomDocmento = documentoElectronico.getNombreDocumento() + ".pdf";
		documento = new DefaultStreamedContent(documentosElectronicosService.getFileRIDE(nomDocmento),
				"application/pdf", nomDocmento);
	}

	public StreamedContent getDocumento() {
		return documento;
	}

	public List<DocumentoElectronico> getListaDocumentosAutorizados() {
		return listaDocumentosAutorizados;
	}

	@PostConstruct
	public void init() {
		mes = Mes.obtenerPorId(fechaFormatoString(new Date()).substring(3, 5));
		anio = Anio.obtenerPorId(fechaFormatoString(new Date()).substring(6, 10));
		documentosElectronicosService.getDocumentosPorPersona();
	}

	public void obtener() {
		listaDocumentosAutorizados = documentosElectronicosService.getDocumentosAutorizados(mes, anio);
	}

	public Mes getMes() {
		return mes;
	}

	public void setMes(Mes mes) {
		this.mes = mes;
	}

	public Anio getAnio() {
		return anio;
	}

	public void setAnio(Anio anio) {
		this.anio = anio;
	}

	public void setDocumento(StreamedContent documento) {
		this.documento = documento;
	}

	public void setListaDocumentosAutorizados(List<DocumentoElectronico> listaDocumentosAutorizados) {
		this.listaDocumentosAutorizados = listaDocumentosAutorizados;
	}
}

src/main/webapp/WEB-INF/template.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<f:facet name="first">
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<meta name="viewport"
			content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
	</f:facet>
	<link rel="icon" type="image/png"
		href="/resources/spark-layout/images/favicon.png" />
	<title>Negosys-<ui:insert name="title" /></title>
	<h:outputScript name="js/layout.js" library="spark-layout" />
	<h:outputScript name="js/funciones.js" library="spark-layout" />
	<ui:insert name="head" />
</h:head>

<h:body>
	<div id="menu-mask"></div>

	<ui:include src="topbar.xhtml" />

	<div id="layout-portlets-cover">
		<p:growl id="mensaje" showDetail="true" life="7000"
			showSummary="false" severity="info, warn, error, fatal" />
		<ui:insert name="content">
	        	Template
	        </ui:insert>
		<div class="layout-portlets-box TexAlCenter">
			<span class="Fs14 gray FontRalewayRegular"> Teléfonos: 2934104
				- 0999308011 | E-mail: <a class="blue"
				href="mailto:soporte@redepronik.com.ec">
					soporte@redepronik.com.ec </a>
			</span> <span class="Fs14 gray FontRalewayRegular Fright"> <a
				href="//facebook.com/redepronik" target="_blank"> <i
					class="fa fa-facebook-square Fs40 blue"></i>
			</a> <a href="//twitter.com/redepronik" target="_blank"
				style="margin-left: 10px;"> <i
					class="fa fa-twitter-square Fs40 blue"></i>
			</a> <a href="//plus.google.com/+RedepronikEc" target="_blank"
				style="margin-left: 10px;"> <i
					class="fa fa-google-plus-square Fs40 blue"></i>
			</a>
			</span> <br></br> <span class="Fs14 gray FontRalewayRegular"> © 2017
				<a class="blue" href="//www.redepronik.com.ec" target="_blank">
					Redepronik Systems </a> Todos Los Derechos Reservados
			</span>
		</div>
	</div>

	<p:ajaxStatus id="ajax" onstart="PF('statusDialog').show()"
		onsuccess="PF('statusDialog').hide()" />
	<p:dialog widgetVar="statusDialog" modal="true" draggable="false"
		closable="false" resizable="false" showHeader="false">
		<p:graphicImage name="images/preloader.gif" library="spark-layout" />
	</p:dialog>

	<h:outputStylesheet name="css/core-layout.css" library="spark-layout" />
	<h:outputStylesheet name="css/font-awesome.css" library="spark-layout" />
	<h:outputStylesheet name="css/animate.css" library="spark-layout" />
	<h:outputStylesheet name="css/spark-layout-blue.css"
		library="spark-layout" />
	<h:outputStylesheet name="css/estilos.css" library="spark-layout" />
</h:body>

</html>

src/main/webapp/WEB-INF/topbar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">


	<div id="layout-topbar" class="ShadowGray">
		<div id="layout-topbar-indent">
			<a href="/views/documentosRecibidos.jsf"><h:graphicImage
					name="images/LOGO.svg" styleClass="Fleft" library="spark-layout"
					id="logo" class="Fleft" /></a> <a href="#"
				id="mobile-menu-button-gray" class="BordRad3 white ShowOnMobile"><i
				class="fa fa-caret-down"></i> Menú</a>

			<ul id="layout-topbar-menu">
				<li><a href="/logout.jsf" class="Animated05"><i
						class="fa fa-sign-out"></i> Salir</a></li>
			</ul>
		</div>
	</div>

</ui:composition>

src/main/webapp/login.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<f:facet name="first">
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<meta name="viewport"
			content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
	</f:facet>
	<link rel="icon" type="image/png"
		href="/resources/spark-layout/images/favicon.png" />
	<title>Negosys</title>
	<h:outputScript name="js/layout.js" library="spark-layout" />
	<h:outputScript name="js/funciones.js" library="spark-layout" />

	<h:outputText value="&lt;!--[if gte IE 9]&gt;" escape="false" />
	<style type="text/css">
/* styles for IE 9 */
</style>
	<h:outputText value="&lt;![endif]--&gt;" escape="false" />

	<ui:insert name="head" />
</h:head>

<h:body>

	<div id="layout-portlets-cover">
		<div
			class="other-pages-box Container40 Responsive50 MarAuto Fnone TexAlCenter ShadowGray MarTop10"
			style="margin-top: 5%; background-image: url(/resources/spark-layout/images/loginpageillust.svg); background-repeat: no-repeat; background-position: center; background-size: cover;">
			<div class="Container90 Fnone MarAuto TexAlCenter">
				<form action='${loginUrl}' method='post' class="login-form">
					<div class="EmptyBox50"></div>
					<h:graphicImage name="images/LOGO.svg" library="spark-layout"
						styleClass="Container80 Fnone MarAuto MarTop20 MarBot10" />
					<div class="EmptyBox20"></div>
					<p:inputText id="username" value="" placeholder="Usuario"
						styleClass="TextAlCenter Container80 Fnone MarAuto Fs18" />
					<div class="EmptyBox10"></div>
					<p:password id="password" value="" placeholder="Contraseña"
						styleClass="TextAlCenter Container80 Fnone MarAuto Fs18"
						feedback="false" />
					<div class="EmptyBox30"></div>
					<input type="hidden" name="${_csrf.parameterName}"
						value="${_csrf.token}" />
					<p:commandButton value="Ingresar"
						styleClass="Container80 Fnone MarAuto Fs16"
						onclick="clickIngresar()" />
					<button id="btnSubmit" type="submit" name="submit"
						style="display: none;" />
					<div class="EmptyBox10"></div>
				</form>

				<div class="EmptyBox50"></div>

			</div>
		</div>
	</div>

	<h:outputStylesheet name="css/core-layout.css" library="spark-layout" />
	<h:outputStylesheet name="css/font-awesome.css" library="spark-layout" />
	<h:outputStylesheet name="css/animate.css" library="spark-layout" />
	<h:outputStylesheet name="css/spark-layout-blue.css"
		library="spark-layout" />
	<h:outputStylesheet name="css/estilos.css" library="spark-layout" />
</h:body>

</html>

src/main/webapp/logout.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template.xhtml">

    <ui:define name="content">
    </ui:define>

</ui:composition>

src/main/webapp/views/documentosRecibidos.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui" template="/WEB-INF/template.xhtml">

	<ui:define name="title">Documentos Electronicos</ui:define>

	<ui:define name="content">
		<p:panel header="Filtro de busqueda" styleClass="margin8">
			<h:form id="formParametrosBusqueda">

				<p:outputLabel value="Mes" styleClass="DispBlock" />
				<p:selectOneMenu id="mes" value="#{documentosRecibidosBean.mes}"
					styleClass="DispBlock Wid90">
					<f:selectItems value="#{documentosRecibidosBean.listaMes}"
						var="mes" itemValue="#{mes}" itemLabel="#{mes.nombre}" />
				</p:selectOneMenu>

				<p:outputLabel value="Año" styleClass="DispBlock" />
				<p:selectOneMenu id="anio" value="#{documentosRecibidosBean.anio}"
					styleClass="DispBlock Wid90">
					<f:selectItems value="#{documentosRecibidosBean.listaAnio}"
						var="anio" itemValue="#{anio}" itemLabel="#{anio.id}" />
				</p:selectOneMenu>
				<div class="EmptyBox10"></div>
				<p:commandButton id="buscar" update=":formTablaDocumentos"
					value="Buscar" actionListener="#{documentosRecibidosBean.obtener}"
					icon="fa fa-search white" />
				<div class="EmptyBox10"></div>
			</h:form>

			<h:form id="formTablaDocumentos">
				<p:dataTable id="tablaDocumentos" var="documento" scrollable="true"
					reflow="true"
					value="#{documentosRecibidosBean.listaDocumentosAutorizados}"
					paginator="true" rows="10"
					paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
					paginatorPosition="bottom"
					emptyMessage="No hay Información Disponible">

					<p:column headerText="Gestionar">

						<p:tooltip for="btnXML" value="Descargar XML" />
						<p:commandButton id="btnXML" ajax="false"
							action="#{documentosRecibidosBean.descargarXML(documento)}"
							icon="fa fa-file-code-o">
							<p:fileDownload value="#{documentosRecibidosBean.documento}" />
						</p:commandButton>

						<p:tooltip for="btnRide" value="Descargar RIDE" />
						<p:commandButton id="btnRide" ajax="false"
							action="#{documentosRecibidosBean.descargarRIDE(documento)}"
							icon="fa fa-file-pdf-o">
							<p:fileDownload value="#{documentosRecibidosBean.documento}" />
						</p:commandButton>
					</p:column>

					<p:column headerText="Nombre" filterBy="#{documento}"
						filterMatchMode="contains" styleClass="centrar">
						<p:outputLabel value="#{documento.nombreDocumento}" />
					</p:column>

					<p:column headerText="Tipo" filterBy="#{documento.tipoDocumento}"
						filterMatchMode="contains" styleClass="centrar">
						<p:outputLabel value=" #{documento.tipoDocumento}" />
					</p:column>

				</p:dataTable>
			</h:form>
		</p:panel>
	</ui:define>
</ui:composition>

src/main/webapp/views/seguridad/404.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	manifest="/negosys/resources/negosys.appcache">

<h:head>
	<f:facet name="first">
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<meta name="viewport"
			content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
	</f:facet>
	<link rel="icon" type="image/png"
		href="/negosys/resources/spark-layout/images/favicon.png" />
	<title>Negosys</title>
	<h:outputScript name="js/layout.js" library="spark-layout" />
	<ui:insert name="head" />
</h:head>

<h:body>

	<div id="layout-portlets-cover">
		<div
			class="other-pages-box Container40 Responsive50 MarAuto Fnone TexAlCenter ShadowGray MarTop10"
			style="margin-top: 5%; background-image: url(/negosys/resources/spark-layout/images/loginpageillust.svg); background-repeat: no-repeat; background-position: center; background-size: cover;">
			<div class="Container90 Fnone MarAuto TexAlCenter margin0">
				<div class="EmptyBox50"></div>
				<h:graphicImage name="images/error-face.svg" library="spark-layout"
					styleClass="MarAuto MarTop20 Wid30" />
				<p class="Fs100 Wid100 DispBlock red">404</p>
				<p class="Wid100 DispBlock Fs30 red">Página no Encontrada!</p>
				<br />
				<p class="Wid100 DispBlock Fs18 red">
					Disculpa, el Recurso está bloqueado <br /> o no fue encontrado. <br />
				</p>
				<div class="EmptyBox30"></div>
				<p:button value="Back to Home" styleClass="Fs16 RedButton"
					href="/views/home.jsf" icon="#{msg['i.atras']}" />
				<div class="EmptyBox50"></div>
			</div>
		</div>
	</div>

	<h:outputStylesheet name="css/core-layout.css" library="spark-layout" />
	<h:outputStylesheet name="css/font-awesome.css" library="spark-layout" />
	<h:outputStylesheet name="css/animate.css" library="spark-layout" />
	<h:outputStylesheet name="css/spark-layout.css" library="spark-layout" />
	<h:outputStylesheet name="css/estilos.css" library="spark-layout" />
</h:body>

</html>

src/main/webapp/views/seguridad/accesoDenegado.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	manifest="/negosys/resources/negosys.appcache">

<h:head>
	<f:facet name="first">
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<meta name="viewport"
			content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
	</f:facet>
	<title>Negosys</title>
	<link rel="icon" type="image/png"
		href="/negosys/resources/spark-layout/images/favicon.png" />
	<h:outputScript name="js/layout.js" library="spark-layout" />
	<ui:insert name="head" />
</h:head>

<h:body>

	<div id="layout-portlets-cover">
		<div
			class="other-pages-box Container40 Responsive50 MarAuto Fnone TexAlCenter ShadowGray MarTop10"
			style="margin-top: 5%; background-image: url(/negosys/resources/spark-layout/images/loginpageillust.svg); background-repeat: no-repeat; background-position: center; background-size: cover;">
			<div class="Container90 Fnone MarAuto TexAlCenter margin0">
				<div class="EmptyBox50"></div>
				<h:graphicImage name="images/access-denied.svg"
					library="spark-layout" styleClass="MarAuto MarTop20 Wid30" />
				<p class="Fs40 Wid100 DispBlock red">Acceso Denegado</p>
				<p class="Wid100 DispBlock Fs30 red">Por favor revisa tus
					Permisos!</p>
				<br />
				<p class="Wid100 DispBlock Fs18 red">
					Disculpa, Tú no tienes acceso para esto.<br />
				</p>
				<div class="EmptyBox30"></div>
				<p:button value="Back to Home" styleClass="Fs16 RedButton"
					href="/views/home.jsf" icon="#{msg['i.atras']}" />
				<div class="EmptyBox50"></div>
			</div>
		</div>
	</div>

	<h:outputStylesheet name="css/core-layout.css" library="spark-layout" />
	<h:outputStylesheet name="css/font-awesome.css" library="spark-layout" />
	<h:outputStylesheet name="css/animate.css" library="spark-layout" />
	<h:outputStylesheet name="css/spark-layout.css" library="spark-layout" />
	<h:outputStylesheet name="css/estilos.css" library="spark-layout" />
</h:body>

</html>

src/main/webapp/views/seguridad/error.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	manifest="/negosys/resources/negosys.appcache">

<h:head>
	<f:facet name="first">
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<meta name="viewport"
			content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
	</f:facet>
	<link rel="icon" type="image/png"
		href="/negosys/resources/spark-layout/images/favicon.png" />
	<title>Negosys</title>
	<h:outputScript name="js/layout.js" library="spark-layout" />
	<ui:insert name="head" />
</h:head>

<h:body>

	<div id="layout-portlets-cover">
		<div
			class="other-pages-box Container40 Responsive50 MarAuto Fnone TexAlCenter ShadowGray MarTop10"
			style="margin-top: 5%; background-image: url(/negosys/resources/spark-layout/images/loginpageillust.svg); background-repeat: no-repeat; background-position: center; background-size: cover;">
			<div class="Container90 Fnone MarAuto TexAlCenter margin0">
				<div class="EmptyBox50"></div>
				<h:graphicImage name="images/error-face.svg" library="spark-layout"
					styleClass="MarAuto MarTop20 Wid30" />
				<p class="Fs40 Wid100 DispBlock red">Error</p>
				<p class="Wid100 DispBlock Fs30 red">Ocurrió una Excepción!</p>
				<br />
				<p class="Wid100 DispBlock Fs18 red">Por favor, contacta a un
					Administrador del Sistema.</p>
				<div class="EmptyBox30"></div>
				<p:button value="Back to Home" styleClass="Fs16 RedButton"
					href="/views/home.jsf" icon="#{msg['i.atras']}" />
				<div class="EmptyBox50"></div>
			</div>
		</div>
	</div>

	<h:outputStylesheet name="css/core-layout.css" library="spark-layout" />
	<h:outputStylesheet name="css/font-awesome.css" library="spark-layout" />
	<h:outputStylesheet name="css/animate.css" library="spark-layout" />
	<h:outputStylesheet name="css/spark-layout.css" library="spark-layout" />
	<h:outputStylesheet name="css/estilos.css" library="spark-layout" />
</h:body>

</html>